CREATE TABLE `tablaperuanaalimento` (
  `id` VARCHAR(191) NOT NULL,
  `codigo` VARCHAR(191) NOT NULL,
  `nombre` VARCHAR(191) NOT NULL,
  `grupo` VARCHAR(191) NULL,
  `energia_kcal` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `energia_kj` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `agua_g` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `proteina_g` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `grasa_total_g` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `carbohidratos_totales_g` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `fibra_dietaria_g` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `calcio_mg` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `fosforo_mg` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `hierro_mg` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `zinc_mg` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `vitamina_a_ug` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `tiamina_mg` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `riboflavina_mg` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `niacina_mg` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `vitamina_c_mg` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `fuente` VARCHAR(191) NOT NULL DEFAULT 'Tablas Peruanas de Composición de Alimentos, 11.ª edición digital, marzo de 2025',
  `estado` TINYINT NOT NULL DEFAULT 1,
  `creado_en` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actualizado_en` DATETIME(3) NOT NULL,

  UNIQUE INDEX `tablaperuanaalimento_codigo_key`(`codigo`),
  INDEX `tablaperuanaalimento_nombre_idx`(`nombre`),
  INDEX `tablaperuanaalimento_grupo_idx`(`grupo`),
  INDEX `tablaperuanaalimento_estado_idx`(`estado`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
