ALTER TABLE `tablaperuanaalimento`
  ADD COLUMN `codigo_grupo` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `codigo_numero` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `estrato` VARCHAR(191) NULL,
  ADD COLUMN `carbohidratos_disp_g` DECIMAL(10, 2) NULL,
  ADD COLUMN `cenizas_g` DECIMAL(10, 2) NULL,
  ADD COLUMN `sodio_mg` DECIMAL(10, 2) NULL,
  ADD COLUMN `potasio_mg` DECIMAL(10, 2) NULL,
  ADD COLUMN `betacaroteno_ug` DECIMAL(12, 2) NULL,
  ADD COLUMN `acido_folico_ug` DECIMAL(10, 2) NULL,
  ADD COLUMN `origen` VARCHAR(191) NOT NULL DEFAULT 'ins_tpca_11_2023',
  MODIFY `energia_kcal` DECIMAL(10, 2) NULL,
  MODIFY `energia_kj` DECIMAL(10, 2) NULL,
  MODIFY `agua_g` DECIMAL(10, 2) NULL,
  MODIFY `proteina_g` DECIMAL(10, 2) NULL,
  MODIFY `grasa_total_g` DECIMAL(10, 2) NULL,
  MODIFY `carbohidratos_totales_g` DECIMAL(10, 2) NULL,
  MODIFY `fibra_dietaria_g` DECIMAL(10, 2) NULL,
  MODIFY `calcio_mg` DECIMAL(10, 2) NULL,
  MODIFY `fosforo_mg` DECIMAL(10, 2) NULL,
  MODIFY `zinc_mg` DECIMAL(10, 2) NULL,
  MODIFY `hierro_mg` DECIMAL(10, 2) NULL,
  MODIFY `vitamina_a_ug` DECIMAL(12, 2) NULL,
  MODIFY `tiamina_mg` DECIMAL(10, 2) NULL,
  MODIFY `riboflavina_mg` DECIMAL(10, 2) NULL,
  MODIFY `niacina_mg` DECIMAL(10, 2) NULL,
  MODIFY `vitamina_c_mg` DECIMAL(10, 2) NULL,
  ADD INDEX `tablaperuanaalimento_codigo_grupo_codigo_numero_idx` (`codigo_grupo`, `codigo_numero`);
